# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tetris.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tetris.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctetris.proto\x12\x06tetris\"q\n\rTetrisMessage\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.tetris.MessageType\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x0c\n\x04seed\x18\x03 \x01(\x05\x12\x0f\n\x07garbage\x18\x04 \x01(\x05\x12\x0f\n\x07results\x18\x05 \x01(\t*\x85\x01\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05READY\x10\x01\x12\t\n\x05START\x10\x02\x12\x08\n\x04LOSE\x10\x03\x12\x0b\n\x07GARBAGE\x10\x04\x12\x10\n\x0cGAME_STARTED\x10\x05\x12\x18\n\x14GAME_ALREADY_STARTED\x10\x06\x12\x10\n\x0cGAME_RESULTS\x10\x07\x32I\n\rTetrisService\x12\x38\n\x04Play\x12\x15.tetris.TetrisMessage\x1a\x15.tetris.TetrisMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tetris_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=140
  _globals['_MESSAGETYPE']._serialized_end=273
  _globals['_TETRISMESSAGE']._serialized_start=24
  _globals['_TETRISMESSAGE']._serialized_end=137
  _globals['_TETRISSERVICE']._serialized_start=275
  _globals['_TETRISSERVICE']._serialized_end=348
# @@protoc_insertion_point(module_scope)
